### PR TITLE
Removed some dashboard redundancy and redesign build

### PR DESCRIPTION
**Pull request by speedingdeer**
There are several improvements mentioned in the commits comments.
Eg. Some redundancy and incorrect POST requests were removed (for dashboard).
The one step missing is to create a build branch (compare my fork build branch for details ) for heroku deployments. This way we don't keep the build assets and bower dependency in repository (they just make commits messy, make difficult to figure the dependency version etc.). Additionally it's easier to manage the automatic heroku deployment. whenever someone pushes to build branch (can be called dist. maybe it's a better naming?) The app should be good to go for staging. For the production it should be still done manually, but from the same build/dist branch.

### CODE REVIEW

**Comment by Adam-JF** [comment]
@speedingdeer If you want to push this to the staging area then feel free. Still not sure what the testing failure is regarding but from the looks of it it's not serious unless i'm very much mistaken.

**Comment by speedingdeer** [comment]
@Adam-JF thanks, I would need to change the heroku config to deploy from an orphaned dist / build branch. I don't want to keep the dependencies and compiled (SASS/coffee) files in the repository. Ive already described it here (it's a kind of model, it's the same what github does for gh-pages)
https://trello.com/c/nHfnJ5Gq/14-apply-updated-build-process
If you are OK with it, I will apply the recipe.

**Comment by speedingdeer** [comment]
@Adam-JF The Travis' complaint is really weird, normally my guess would be an expired token or something like this but here it's clearly about the jwt config which hasn't changed.

**Comment by Adam-JF** [comment]
@speedingdeer happy for you to go ahead with whats described in https://trello.com/c/nHfnJ5Gq/14-apply-updated-build-process

With regards to the Travis complaint i've asked for some feedback and will let you know what comes of it - does seem a bit odd and I can't really comment on it.

**Comment by speedingdeer** [comment]
@Adam-JF Oh, you were faster than me correcting typos. The card was still wip ;). Didn't know someone else is doing the late shift.
I'll apply the recipe then. Thanks!
Do you know what has to be a travis user to lookup a config? Can we get an admin or something? The issue is probably just to look into what it's struggling with and update some variable.

**Comment by speedingdeer** [comment]
Going to deploy, closing PR.

**Pull request merged**
